name: reusable_editor
description: "A modular file editor package for Flutter with support for Firebase and REST API storage, including upload/delete functionality, state management cubits, and UI helpers."
version: 1.0.3

homepage: https://geniecodersrc.github.io/reusable_editor/
repository: https://github.com/GenieCoderSrc/reusable_editor
issue_tracker: https://github.com/GenieCoderSrc/reusable_reusable_editor/issues
documentation: https://geniecodersrc.github.io/reusable_editor/



environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  exception_type: ^0.0.3
  i_tdd: ^0.0.1
  fire_storage_impl: ^0.0.2
  get_it_di_global_variable: ^0.0.5
  reusable_app_bar: ^0.0.1
  reusable_image_widget: ^0.0.2
  navigation_without_context: ^0.0.3+1

  i_validator: ^1.0.4
  dartz: ^0.10.1
  flutter_bloc: ^9.1.0
  provider: ^6.1.5
  equatable: ^2.0.7
  bloc: ^9.0.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  file_picker: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

example:
  path: example
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
